---
apiVersion: "v1"
kind: "Service"
metadata:
  labels:
    app: "turbine-server"
    expose: "true"
  name: "turbine-server"
spec:
  ports:
  - name: "http"
    port: 80
    protocol: "TCP"
    targetPort: 8080
  selector:
    app: "turbine-server"
  type: "LoadBalancer"
