---
apiVersion: "extensions/v1beta1"
kind: "Deployment"
metadata:
  labels:
    app: "turbine-server"
  name: "turbine-server"
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: "turbine-server"
    spec:
      containers:
      - env:
        - name: "KUBERNETES_NAMESPACE"
          valueFrom:
            fieldRef:
              fieldPath: "metadata.namespace"
        image: gcr.io/kubeflix-poc/turbine-server-app:v3
        imagePullPolicy: "IfNotPresent"
        livenessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 180
        name: "turbine-server"
        ports:
        - containerPort: 8080
          name: "http"
        - containerPort: 8778
          name: "jolokia"
        readinessProbe:
          httpGet:
            path: "/health"
            port: 8080
          initialDelaySeconds: 10
